In [17]:
import numpy as np

* Faster and easier, and more visual then looping throug things

* What is the last problem

* Mainly for linear 

### generating an array with numpy

In [47]:
full_array = np.full((3, 6, 5), range(2, 12, 2))

In [64]:
n_array = np.arange(1, 5)

In [67]:
n_array[1]

2

In [ ]:
### know the location in memory of the starting of n_array
# 7654
# 7661
# 7668



In [69]:
type(n_array.astype('<U21')[0])

numpy.str_

In [66]:
np.append(np.arange(1, 5), '1')

array(['1', '2', '3', '4', '1'], dtype='<U21')

In [20]:
np.random.normal(0, .5)

0.10109705998285198

In [71]:
str(121221)

'121221'

In [46]:
grid = np.indices((2, 3))
grid

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

### Retrieving Data

In [73]:
full_array = np.full((6, 5), range(2, 12, 2))

In [77]:
full_array

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])

In [98]:
np.append(full_array, np.arange(1, 6)).shape

(35,)

In [108]:
tuple([35])

(35,)

In [112]:
np.arange(1, 4)

array([1, 2, 3])

In [110]:
np.append(full_array, np.arange(1, 11)).reshape(40, 1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [118]:
my_matrix = full_array.reshape(5, 6)

In [119]:
my_matrix

array([[ 2,  4,  6,  8, 10,  2],
       [ 4,  6,  8, 10,  2,  4],
       [ 6,  8, 10,  2,  4,  6],
       [ 8, 10,  2,  4,  6,  8],
       [10,  2,  4,  6,  8, 10]])

In [122]:
3 % 2 == 0

False

In [125]:
matrix_of_booleans = my_matrix % 4 == 0

In [127]:
my_matrix

array([[ 2,  4,  6,  8, 10,  2],
       [ 4,  6,  8, 10,  2,  4],
       [ 6,  8, 10,  2,  4,  6],
       [ 8, 10,  2,  4,  6,  8],
       [10,  2,  4,  6,  8, 10]])

In [139]:
my_matrix[:, 1] == 4

array([ True, False, False, False, False])

In [138]:
my_matrix[]

array([], shape=(0, 5, 6), dtype=int64)

In [126]:
matrix_of_booleans

array([[False,  True, False,  True, False, False],
       [ True, False,  True, False, False,  True],
       [False,  True, False, False,  True, False],
       [ True, False, False,  True, False,  True],
       [False, False,  True, False,  True, False]])

In [133]:
my_matrix[my_matrix % 4 == 0]

array([4, 8, 4, 8, 4, 8, 4, 8, 4, 8, 4, 8])

In [78]:
full_array.shape

(6, 5)

In [1]:
list_of_msas = 'https://en.wikipedia.org/wiki/List_of_metropolitan_statistical_areas'

In [3]:
import pandas as pd

In [9]:
msa_df = pd.read_html(list_of_msas)[1]

In [21]:
msa_npa = msa_df
msa_npa.values

array([['Rank', 'Metropolitan\xa0statistical\xa0area', '2017 Estimate',
        '2010 Census', '% Change',
        'Encompassing combined statistical\xa0area'],
       [nan, 'New York-Newark-Jersey City, NY-NJ-PA MSA', '20320876',
        '19567410', '+3.85%', 'New York-Newark, NY-NJ-CT-PA CSA'],
       [nan, 'Los Angeles-Long Beach-Anaheim, CA MSA', '13353907',
        '12828837', '+4.09%', 'Los Angeles-Long Beach, CA CSA'],
       ...,
       [nan, 'Lewiston, ID-WA MSA', '62920', '60888', '+3.34%', nan],
       [nan, 'Enid, OK MSA', '61581', '60580', '+1.65%', nan],
       [nan, 'Carson City, NV MSA', '54745', '55274', '−0.96%',
        'Reno-Carson City-Fernley, NV CSA']], dtype=object)

In [16]:
msa_npa[1:, 1:]

array([['New York-Newark-Jersey City, NY-NJ-PA MSA', '20320876',
        '19567410', '+3.85%', 'New York-Newark, NY-NJ-CT-PA CSA'],
       ['Los Angeles-Long Beach-Anaheim, CA MSA', '13353907', '12828837',
        '+4.09%', 'Los Angeles-Long Beach, CA CSA'],
       ['Chicago-Naperville-Elgin, IL-IN-WI MSA', '9533040', '9461105',
        '+0.76%', 'Chicago-Naperville, IL-IN-WI CSA'],
       ...,
       ['Lewiston, ID-WA MSA', '62920', '60888', '+3.34%', nan],
       ['Enid, OK MSA', '61581', '60580', '+1.65%', nan],
       ['Carson City, NV MSA', '54745', '55274', '−0.96%',
        'Reno-Carson City-Fernley, NV CSA']], dtype=object)

In [23]:
pd.read_csv('presidents.csv').values

array([[1, 'George Washington', 189],
       [2, 'John Adams', 170],
       [3, 'Thomas Jefferson', 189],
       [4, 'James Madison', 163],
       [5, 'James Monroe', 183],
       [6, 'John Quincy Adams', 171],
       [7, 'Andrew Jackson', 185],
       [8, 'Martin Van Buren', 168],
       [9, 'William Henry Harrison', 173],
       [10, 'John Tyler', 183],
       [11, 'James K. Polk', 173],
       [12, 'Zachary Taylor', 173],
       [13, 'Millard Fillmore', 175],
       [14, 'Franklin Pierce', 178],
       [15, 'James Buchanan', 183],
       [16, 'Abraham Lincoln', 193],
       [17, 'Andrew Johnson', 178],
       [18, 'Ulysses S. Grant', 173],
       [19, 'Rutherford B. Hayes', 174],
       [20, 'James A. Garfield', 183],
       [21, 'Chester A. Arthur', 183],
       [23, 'Benjamin Harrison', 168],
       [25, 'William McKinley', 170],
       [26, 'Theodore Roosevelt', 178],
       [27, 'William Howard Taft', 182],
       [28, 'Woodrow Wilson', 180],
       [29, 'Warren G. Harding', 183

### Resources

In [15]:
box_score = 'http://www.espn.com/nba/boxscore?gameId=401070872'

list_of_msas = 'https://en.wikipedia.org/wiki/List_of_metropolitan_statistical_areas'

* presidential heights